steps:
  # Clones the repo. This is an explicit step to preserve symlinks for Windows.
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
      checkLatest: 'true'
    displayName: 'Install Node.js'

  # Run npm ci by default unless NPM_INSTALL is set
  - script: npm i
    displayName: 'Install dependencies'


  - script: npm test
    displayName: 'Run tests'
